#!/bin/bash

function encode {
    echo "$input" | base64 | sed -r 's@\+@-@g; s@/@_@g; s@=+$@@g'
    return 0
}

function decode {
    echo "$input" | sed -r 's@-@+@g; s@_@/@g' | base64 -d
    return 0
}

function usage {
cat << EOF
Usage: $(basename $0) [-h] [-d]
  (default) encode from stdin
  -d        decode from stdin
  -h        show help and exit
EOF
}

if [ "$1" = '-h' ]; then
    usage
    exit
fi

input=$(cat)

case $1 in
    -d) decode 2> /dev/null;;
     *) encode 2> /dev/null;;
esac
