#!/bin/bash

for i in `ls /sys/class/scsi_host/`; do
    echo "- - -" > /sys/class/scsi_host/$i/scan
done

for i in `ls /sys/class/scsi_device/`; do
    echo "1" > /sys/class/scsi_device/$i/device/rescan
done
